<style>
    .message { margin: 5px 0 0 5px; border: 2px solid grey; width: 950px; min-height: 100px;}
    .indent { height: 80px;}
    .author { margin-left: 10px; }
    .text { padding-left: 15px; padding-top: 15px; }
    .date {color: grey; font-size: 11px;}
    .admin a { color: #46468b; float: right; padding-right: 15px; }
    .logout a { color: #aa4542; float: right; padding-right: 650px; }
</style>

<?php
/** @var $message \App\Model\Eloquent\Message */
/** @var $user \App\Model\Eloquent\User */
$user = $this->user;
?>

Привет, <?=$user->getName();?>
<div class="logout">
    <a href="/index.php/logout">Выход</a>
</div>

<br><br>

<?php if($messages = $this->messages): ?>
    <?php foreach ($messages as $message): ?>
        <div class="message">
            <? if($user->isAdmin()): ?>
            <div class="admin">
                <a href="/index.php/admin/deleteMessage/?id=<?=$message->getId();?>">Удалить сообщение</a>
            </div>
            <? endif; ?>
            <span class="date"><?=$message->getMessageDateTime();?> </span>
            <? if($author = $message->getAuthor()):?>
                <span class="author"><?=htmlspecialchars($author->getName());?></span>
            <? else: ?>
                <span class="author">Сообщение от удаленного пользователя</span>
            <? endif; ?>
            <div class="text"><?=htmlspecialchars(nl2br($message->getText()));?></div>
            <? if($message->getImage()):?>
                <div><img src="/images/<?=$message->getImage();?>" style="width: 150px;"></div>
            <? endif;?>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    Сообщения отсутствуют :(
<?php endif; ?>

<div class="indent">
</div>

Добавить сообщение:
<form enctype="multipart/form-data" action="/index.php/blog/addMessage" method="post">
    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea><br><br>
    Изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>